# Generated by Django 3.2.9 on 2022-03-26 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholicProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, validators=[django.core.validators.MaxLengthValidator(16)], verbose_name='NAME')),
                ('product_type', models.CharField(max_length=16, validators=[django.core.validators.MaxLengthValidator(16)], verbose_name='PRODUCT_TYPE')),
                ('manufacturer', models.CharField(max_length=16, validators=[django.core.validators.MaxLengthValidator(16)], verbose_name='MANUFACTURER')),
                ('degree', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='DEGREE')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='PRICE')),
            ],
        ),
        migrations.AddConstraint(
            model_name='alcoholicproduct',
            constraint=models.UniqueConstraint(fields=('name', 'product_type', 'manufacturer'), name='unique_keys'),
        ),
    ]
